### ISSUE TITLE
Rename BooleanInput component to Checkbox

### ISSUE THREAD

**Issue by Zenahr** [playcanvas/pcui#12]
https://playcanvas.github.io/pcui/components/boolean-input/

Is there anything BooleanInput does that differs from regular Checkboxes? If not, I'd argue that it would be best to rename it to Checkbox. This way, everyone who's familiar with basic UI components (UX/UI designers, web developers etc.) will know right away what this is meant to do.

**Comment by ellthompson** [comment]
The boolean input component contains two different views; checkboxes and toggles. That is why it has a more generic name. I agree that the current naming isn't ideal for users though. The playcanvas editor get's around this by using name alias' for some components. Perhaps something similar needs to be implemented in PCUI.

**Comment by Zenahr** [comment]
> The boolean input component contains two different views; checkboxes and toggles. That is why it has a more generic name. I agree that the current naming isn't ideal for users though. The playcanvas editor get's around this by using name alias' for some components. Perhaps something similar needs to be implemented in PCUI.

This makes sense. I'll close this for now since this particular issue has been commented on sufficiently.
