### ISSUE TITLE
An example of how to use framework with ReactJS

### ISSUE THREAD

**Issue by HusakYurii** [playcanvas/pcui#146]
I was amazed by the framework when I found out about it! However, when I tried to use the framework as npm dependency in my react project I couldn't make it work. 
I set up a generic react project by running scripts the ReactJS library provides out of the box and added the PCUI as an[ npm dependency.](https://www.npmjs.com/package/@playcanvas/pcui). Then I followed the instructions describing how to use the framework components as the react components.
But `import Label from 'dist/Label/component';`  led to a warning `Cannot find module 'dist/Label/component' or its corresponding type declarations.`

I would like PCUI to have some doc about how to use the framework with ReactJS or a boilerplate for React + PCUI projects 
a dev can start off.
I can assist with writing that doc or boilerplate if you are short of hands
😉

**Comment by ellthompson** [comment]
Hi @HusakYurii 

There is a guide in our docs for React + PCUI: https://playcanvas.github.io/pcui/react/
And you can see a more extensive example here: https://playcanvas.github.io/pcui/examples/todo/

It'd be great if you could offer any other suggestions on how we may need to expand the React documentation.

**Comment by HusakYurii** [comment]
Hey @ellthompson !
Thanks for getting back to my question.
I tried to use the PCUI as the examples in the doc show, but the import statements showed errors. I already forgot how I tried to use it, but I tried multiple ways  🤔
Has the documentation been updated since 25 Oct 2021

**Comment by willeastcott** [comment]
Hi @HusakYurii. This issue has gone a little bit stale. PCUI has updated significantly in the last couple of weeks. I would suggest trying again. If there are still problems, we will investigate.

**Comment by willeastcott** [comment]
Closing as I suspect this is no longer an issue. But feel free to reopen if you are continuing to experience problems.
