### ISSUE TITLE
PCUI source fails to build from NPM build sites

### ISSUE THREAD

**Issue by rpaladin** [playcanvas/pcui#154]
## Comments

When I attempt to use a CDN package build site I get package errors about PCUI failing to build.
@yaustar was able to confirm that PCUI can still be built without errors if done locally.

I hope I do not offend anyone by sharing this but PCUI at SkyPack does have a relatively low package setup rating:

<img src="https://forum-files-playcanvas-com.s3.dualstack.eu-west-1.amazonaws.com/original/3X/b/d/bdcffb893ecccb25ca805b5e9778b002b7dce383.png">

## Build Errors from CodePen

<img src="https://forum-files-playcanvas-com.s3.dualstack.eu-west-1.amazonaws.com/original/3X/1/0/10432fb58f6ad254aec159a490c14c319afb993d.png">

<img src="https://forum-files-playcanvas-com.s3.dualstack.eu-west-1.amazonaws.com/original/3X/5/e/5eecb76fef3e01c16d515706ffd646dcc4552e83.png">

## CodePen Reproducible Errors Project

https://codepen.io/RandomPanda/pen/ExwrPqB

## Possible Solutions

The <kbd>exports</kbd> argument is missing in the PCUI <kbd>package.json</kbd>.

## Package Build Sites (using CDN from SkyPack)

Hosting provider: <https://codepen.io>
Package build sites: <https://skypack.dev> & <https://www.jsdelivr.com>

## Forum Thread

<https://forum.playcanvas.com/t/pcui-framework-build-source-failing/23793/1>

## Final Comments

It would be great if this issue was resolved because some people who choose to use the PlayCanvas Engine-Only CDN approach will also like to use PCUI perhaps. Not to mention that the PlayCanvas Editor only allows its own PCUI.js in the editor and not at runtime.

**Comment by yaustar** [comment]
> Not to mention that the PlayCanvas Editor only allows its own PCUI.js in the editor and not at runtime.

Not sure what you mean by this? You can use PCUI.js at runtime as seen here: https://playcanvas.com/project/808700/overview/pcui-game-inspector

**Comment by rpaladin** [comment]
Sorry, I was referring to the Editor PCUI folder in general that is filled with compiled JS files. Should have clarified that.

<img src="https://user-images.githubusercontent.com/69180012/151042116-e6eaa0b0-3ae4-4c33-b89f-f937dfd4b670.png">

**Comment by willeastcott** [comment]
I believe this is now fixed. See:

https://codepen.io/playcanvas/pen/LYBxwOx

**Comment by willeastcott** [comment]
Also, I've migrated the PCUI examples to use SkyPack now and it works perfectly:

https://github.com/playcanvas/pcui/pull/262/files

As for the low SkyPack score, it was complaining that the `package.json` was missing the keywords property, so I've added it here:

https://github.com/playcanvas/pcui/pull/263
