### ISSUE TITLE
Fix Typescript declarations

### ISSUE THREAD

**Issue by querielo** [playcanvas/pcui#167]
**Describe the bug**
There are a few known problems:
1. Interface `IContainer` is not implemented. So, should we use `extends Container` instead of `implements IContainer`? (see https://github.com/playcanvas/pcui/blob/main/src/Panel/index.js#L46)
2. Interfaces are not imported to the file, so, probably, JSDoc doesn't know where to take interfaces I*. Maybe this can help it:
```
/** @typedef {import('../interfaces/IFlex')} IFlex */
/** @typedef {import('../interfaces/IGrid')} IGrid */
/** @typedef {import('../interfaces/ICollapsible')} ICollapsible */
/** @typedef {import('../interfaces/IScrollable')} IScrollable */
/** @typedef {import('../interfaces/IResizable')} IResizable */
```
3. Descriptions of classes in pcui.d.ts does not have fields if they implement interfaces.
<img width="837" alt="Screen Shot 2022-06-13 at 12 20 22" src="https://user-images.githubusercontent.com/104348270/173312668-18d8b119-57af-4f5f-b7a3-573396575830.png">
We can add the fields, check @mixin/@mixes declarations, or try to use default *.d.ts generator from TypeScript compiler. Like:

```
npx -p typescript tsc src/**/*.js --declaration --allowJs --emitDeclarationOnly --outDir [DESTINATION]
```

Right now, we have to use **@ts-ignore** everywhere where we need fields from interfaces in TS code

```
// @ts-ignore
this.collapsible = true;
```
4. The new version of the library (v.2.3.2) from NPM does not have .d.ts file
<img width="159" alt="Screen Shot 2022-06-13 at 17 15 27" src="https://user-images.githubusercontent.com/104348270/173362196-08edab7f-eb38-4073-a524-f9b7f4b977f9.png">

**Comment by querielo** [comment]
@ellthompson Could you look at it? Especially, on the 4 point.

**Comment by willeastcott** [comment]
@querielo PCUI 2.3.3 was just released:

https://github.com/playcanvas/pcui/releases/tag/v2.3.3

**Comment by ellthompson** [comment]
Closing this as these interfaces are no longer used after this PR was merged: https://github.com/playcanvas/pcui/pull/190
