### ISSUE TITLE
No color component?

### ISSUE THREAD

**Issue by baizp** [playcanvas/pcui#172]
Playcanvas editor has color components. Does pcui seem to have no color components?

**Comment by baizp** [comment]
> I'm afraid not. It's a custom component in the PlayCanvas Editor

Oh, so it is. How can pcui also have color component?

**Comment by yaustar** [comment]
There have been some discussions about moving it from the Editor to PCUI but for the short term, you could look at the Editor code via devtools and try to grab the code for your own project :)

**Comment by baizp** [comment]
> 已经有一些关于将其从编辑器移至 PCU​​I 的讨论，但在短期内，您可以通过 devtools 查看编辑器代码并尝试为您自己的项目获取代码:)

OK, thank you for your reply!
