### ISSUE TITLE
TreeViewItem disappears when child of another Item

### ISSUE THREAD

**Issue by mapacarta** [playcanvas/pcui#207]
After the latest update TreeViewItems disappear when they are child of another TreeViewItem. Here is the code I am using for this:

```
const { Container, TreeView, TreeViewItem } = require("@playcanvas/pcui");

let container = new Container();
document.body.appendChild(container.dom);

let treeView = new TreeView({
  allowDrag: true,
  allowReordering: true,
  allowRenaming: true,
  enabled: true,
  height: null,
  resizeMax: 0,
  resizeMin: 0,
  tabIndex: 0,
  width: null,
});
container.append(treeView);


let sceneItem = new TreeViewItem({
  text: "Scene",
  enabled: true,
});
treeView.append(sceneItem);


let item = new TreeViewItem({
  text: "test",
  enabled: true,
});

sceneItem.append(item);

let item2 = new TreeViewItem({
  text: "test2",
  enabled: true,
});

item.append(item2);
```

Here is how it looks like. item2 appears in the elements but it is hidden.

![image](https://user-images.githubusercontent.com/425105/208916514-e1ea89de-64a8-4564-a0f6-bcb7fbe6394a.png)

**Comment by willeastcott** [comment]
Hi @mapacarta - we've made a few releases of PCUI over the last few days. Can you be explicit about when this broke exactly? What was the last working version number for the library?

**Comment by mapacarta** [comment]
Hi,
It was working fine on 2.8.0, a few days ago I upgraded to 2.10.0 and it is broken now

**Comment by ellthompson** [comment]
It looks like your code example is working on 3.0.0:
https://codepen.io/ellt92/pen/LYBVrvd

**Comment by mapacarta** [comment]
I didn't see the 3.0.0 release, I will check it asap. Thanks

**Comment by mapacarta** [comment]
It is working fine thanks

**Comment by willeastcott** [comment]
Fantastic. Thanks for letting us know!
