### ISSUE TITLE
PCUI guide link in pcui readme gives 404

### ISSUE THREAD

**Issue by Sirahi** [playcanvas/pcui#335]
PCUI guide link in pcui readme gives 404

At the end of [PCUI - User Interface Component Library for the Web](https://github.com/playcanvas/pcui?tab=readme-ov-file#pcui---user-interface-component-library-for-the-web) section, it says 
**A full guide to using the PCUI library can be found [here](https://playcanvas.github.io/pcui).**

The given link for the full guide gives 404.

**Expected behavior**
The link should take you to the pcui guide.

**Screenshots**
![image](https://github.com/playcanvas/pcui/assets/22786724/fe77cebf-3e08-4358-87e8-9cbe07e46348)

**Desktop**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Chrome Version 120.0.6099.109

**Comment by willeastcott** [comment]
Yes, @slimbuck mentioned this week that he might have caused this by accident. We'll restore it ASAP... Thanks for logging this though.

**Comment by impressivewebs** [comment]
@willeastcott Would be great to have this corrected soon. This library was one of the most clicked tools in my newsletter (https://webtoolsweekly.com/) this year and I'm planning to add it to a "Top Tools" list in the next couple of issues (this Thursday and next Thursday). I'll probably also include it in an article that will be published elsewhere. But I can only include it if the pages are working correctly. 😃

**Comment by willeastcott** [comment]
@impressivewebs We're addressing this this morning.

**Comment by mvaligursky** [comment]
Fixed, all works now, thanks for the reports.
