### ISSUE TITLE
Panel Header is duplicated when using components in react app

### ISSUE THREAD

**Issue by yorschor** [playcanvas/pcui#358]
I noticed this while playing around with PCUI in a NextJS app. 
The following code 
`export default function App() {
    return (
        <Panel
            headerText="Foo Basadsadfr"
            collapsible
            collapseHorizontally
            resizable="right"
            width={150}
            resizeMin={150}
            resizeMax={300}/>
    )
}` 
results in this on my side 
![image](https://github.com/playcanvas/pcui/assets/25516638/7a510234-f6f5-4dd1-a0f3-9d476f6f5bfb)

I assume this is perhaps due to how react manages the lifetime? Its working fin in the current example so I assumed that its a react specific.

**Comment by marklundin** [comment]
Yep, this looks like a valid issue. Repro https://stackblitz.com/edit/vitejs-vite-vrt9bt?file=src%2FApp.tsx

**Comment by yorschor** [comment]
Appears to be fixed by #360 Thanks a lot :)
