### ISSUE TITLE
PCUI are not valid JSX components when imported to a Preact project

### ISSUE THREAD

**Issue by sr229** [playcanvas/pcui#380]
**Describe the bug**

We are trying to use PCUI on our preact project, however, it seems that trying to import it right now makes it think the import is not a valid JSX component.

**To Reproduce**
1. Start a base Preact project with TypeScript
2. Install PCUI (ensure `@preact/compat` is installed)
3. Use at least one component in the project

**Expected behavior**

**Screenshots**
<img width="904" alt="image" src="https://github.com/user-attachments/assets/8ebae64b-677c-4ff0-b376-0b64c00f762c">

**Desktop (please complete the following information):**
 - OS: macOS Seqouia
 - Browser Edge
 - Version 120

**Additional context**

**Comment by willeastcott** [comment]
@sr229 I just attempted to reproduce this issue but it seemed to work fine. Here's what I did:


1. Created a new Preact project with TypeScript:

```bash
npm create vite@latest my-preact-app -- --template preact-ts
cd my-preact-app
```

2. Installed dependencies:

```bash
# Install base dependencies
npm install

# Install PCUI and Preact compat
npm install @playcanvas/pcui @preact/compat
```

3. Created a test component in `src/app.tsx`:

```typescript
import { Button } from '@playcanvas/pcui/react'

export function App() {
  return (
    <div>
      <h1>PCUI Test</h1>
      <Button text="Click me" />
    </div>
  )
}
```

4. Ran the project:

```bash
npm run dev
```

I saw this:

![image](https://github.com/user-attachments/assets/b7c3652e-12b7-45bb-9ab8-ec7e9bfd167b)

**Comment by sr229** [comment]
Let me see if I can reproduce it again, I tried it against the latest version at the time this was written

**Comment by sr229** [comment]
I've managed to reproduce the sample app properly, and found out it's a misconfiguration in the project. Closing as fixed.

**Comment by willeastcott** [comment]
@sr229 Fantastic! I'm glad it is now resolved. 😄
